/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.*;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import java.awt.*;


/**
 *
 * @author Bernardo
 */
public class PainelNumeroLinhas extends javax.swing.JPanel {
    private JTextPane textPane;

    public PainelNumeroLinhas(JTextPane textPane) {
        this.textPane = textPane;

        textPane.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                repaint();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                repaint();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                repaint();
            }
        });
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.setFont(textPane.getFont());
        FontMetrics fm = g.getFontMetrics();
        int lineHeight = fm.getHeight();
        int lineCount = getLineCount();

        setPreferredSize(new Dimension(55, lineHeight * lineCount));

        for (int i = 0; i < lineCount; i++) {
            String numeroLinha = String.valueOf(i + 1);
            int y = (i + 1) * lineHeight - fm.getDescent();
            g.drawString(numeroLinha, 5, y);
        }
    }

    // Método para contar linhas no JTextPane
    private int getLineCount() {
        String text = textPane.getText();
        return text.isEmpty() ? 1 : text.split("\n").length;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
